import type { Metadata } from "next";
import { Inter, Fraunces, Kalam } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import PageTransition from "@/components/layout/PageTransition";
import FloatingSocial from "@/components/ui/FloatingSocial";
import InkPenCursor from "@/components/ui/InkPenCursor";
import GoogleAnalytics from "@/components/GoogleAnalytics";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  display: "swap",
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
});

const kalam = Kalam({
  variable: "--font-kalam",
  subsets: ["latin"],
  display: "swap",
  weight: ['300', '400', '700'],
});

export const metadata: Metadata = {
  metadataBase: new URL('https://calvinliew.space'),
  title: {
    default: "Calvin Liew — AI Workflows Product Analyst",
    template: "%s | Calvin Liew"
  },
  description: "AI Workflows Product Analyst at Sanofi building AI agents, RAG pipelines, and enterprise data products. Portfolio: SaaSScout, PantryPilot, and more. UofT · Toronto.",
  keywords: [
    "Calvin Liew",
    "AI Workflows Product Analyst",
    "AI Product Manager",
    "AI Agents",
    "RAG Pipeline",
    "Retrieval-Augmented Generation",
    "Agentic AI",
    "Product Analyst",
    "Product Strategy",
    "Portfolio",
    "Sanofi",
    "SupRM Intelligence",
    "SaaSScout",
    "PantryPilot",
    "University of Toronto",
    "Toronto",
    "LLM",
    "Snowflake",
    "Data Analysis",
    "UX Design",
    "Enterprise AI",
    "Procurement Analytics",
  ],
  authors: [{ name: "Calvin Liew", url: "https://calvinliew.space" }],
  creator: "Calvin Liew",
  alternates: {
    canonical: 'https://calvinliew.space',
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: 'https://calvinliew.space',
    siteName: "Calvin Liew Portfolio",
    title: "Calvin Liew — AI Workflows Product Analyst",
    description: "Building AI agents, RAG pipelines, and data products at Sanofi. Portfolio of shipped work in agentic AI, product design, and data analysis.",
    // Image is auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Calvin Liew — AI Workflows Product Analyst",
    description: "Building AI agents, RAG pipelines, and data products at Sanofi. Portfolio of shipped work in agentic AI, product design, and data analysis.",
    creator: "@calvinliew",
    // Image inherits from opengraph-image.tsx
  },
  // Favicon is auto-generated by src/app/icon.tsx
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.variable} ${fraunces.variable} ${kalam.variable} antialiased`}
      >
        {process.env.NEXT_PUBLIC_GA_ID && (
          <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID} />
        )}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:bg-ink focus:text-paper focus:rounded-lg"
        >
          Skip to content
        </a>
        <Header />
        <PageTransition>{children}</PageTransition>
        <Footer />
        <FloatingSocial />
        <InkPenCursor />
      </body>
    </html>
  );
}
