import type { Metadata } from "next";
import { Inter, Fraunces, Kalam } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import PageTransition from "@/components/layout/PageTransition";
import FloatingSocial from "@/components/ui/FloatingSocial";
import InkPenCursor from "@/components/ui/InkPenCursor";
import GoogleAnalytics from "@/components/GoogleAnalytics";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  display: "swap",
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
});

const kalam = Kalam({
  variable: "--font-kalam",
  subsets: ["latin"],
  display: "swap",
  weight: ['300', '400', '700'],
});

export const metadata: Metadata = {
  metadataBase: new URL('https://calvinliew.space'),
  title: {
    default: "Calvin Liew - Product Analyst & Designer",
    template: "%s | Calvin Liew"
  },
  description: "Product Analyst and Designer building intelligent products at the intersection of technology, design, and business strategy. Experience in UI/UX design, data analysis, and product development.",
  keywords: ["Product Analyst", "Product Designer", "UI/UX Designer", "Portfolio", "Calvin Liew", "University of Toronto", "Sanofi", "Data Analysis"],
  authors: [{ name: "Calvin Liew" }],
  openGraph: {
    type: "website",
    locale: "en_US",
    url: 'https://calvinliew.space',
    siteName: "Calvin Liew Portfolio",
    title: "Calvin Liew - Product Analyst & Designer",
    description: "Product Analyst and Designer building intelligent products at the intersection of technology, design, and business strategy.",
    // Image is auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Calvin Liew - Product Analyst & Designer",
    description: "Product Analyst and Designer building intelligent products at the intersection of technology, design, and business strategy.",
    // Image inherits from opengraph-image.tsx
  },
  // Favicon is auto-generated by src/app/icon.tsx
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.variable} ${fraunces.variable} ${kalam.variable} antialiased`}
      >
        {process.env.NEXT_PUBLIC_GA_ID && (
          <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID} />
        )}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:bg-ink focus:text-paper focus:rounded-lg"
        >
          Skip to content
        </a>
        <Header />
        <PageTransition>{children}</PageTransition>
        <Footer />
        <FloatingSocial />
        <InkPenCursor />
      </body>
    </html>
  );
}
